- name: Check Existing VLANs
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show vlan Command
      arista.eos.eos_command:
        commands:
          - command: show vlan 10
            output: json
      register: show_vlan_response
    - name: Print show vlan Response
      ansible.builtin.debug:
        var: show_vlan_response.stdout[0].vlans